#!/usr/bin/env node

const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

(async () => {
  // 1) Launch Chrome (visible so you can log in/interact if needed)
  const browser = await puppeteer.launch({
    headless: false,
    userDataDir: path.resolve(__dirname, 'userdata')
  });
  const page = await browser.newPage();

  // 2) Go to Amazon UK
  await page.goto('https://www.amazon.co.uk', { waitUntil: 'networkidle2' });

  // 3) Wait for you to press Enter
  console.log('✓ Page loaded. Press Enter to export all cookies to cookies.txt');
  process.stdin.setEncoding('utf8');
  process.stdin.once('data', async () => {

    // 4) Grab all cookies
    const cookies = await page.cookies();

    // 5) Build Netscape‐format file
    let output = [
      '# Netscape HTTP Cookie File',
      '# Generated by Puppeteer',
      ''
    ].join('\n');

    for (const c of cookies) {
      // domain: prefix with dot if subdomains allowed
      const domain = c.hostOnly ? c.domain : (c.domain.startsWith('.') ? c.domain : '.' + c.domain);
      const includeSubdomains = c.hostOnly ? 'FALSE' : 'TRUE';
      const path = c.path;
      const secure = c.secure ? 'TRUE' : 'FALSE';
      // expires is seconds since epoch, or -1 for session cookies
      const expires = (c.expires && c.expires > 0) ? Math.floor(c.expires) : 0;
      // name and value
      const name = c.name;
      const value = c.value;

      output += [
        domain,
        includeSubdomains,
        path,
        secure,
        expires,
        name,
        value
      ].join('\t') + '\n';
    }

    // 6) Write out
    fs.writeFileSync('cookies.txt', output);
    console.log('✓ cookies.txt written');
    await browser.close();
    process.exit(0);
  });
})();
